package com.yaozhitech.baobei.article.domain;

import java.io.Serializable;
import java.util.Date;

public class BiHuaxiang implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.id
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.date_cd
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Date dateCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.product_system
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private String productSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.new_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer newUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.old_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer oldUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.membercard_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer membercardUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.person_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer personUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.inst_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer instUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.class_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer classUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.zfb_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer zfbUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.wxapp_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer wxappUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.wxweb_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Integer wxwebUserCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.crt_time
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_huaxiang.upd_time
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_huaxiang
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.id
     *
     * @return the value of bi_huaxiang.id
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.id
     *
     * @param id the value for bi_huaxiang.id
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.date_cd
     *
     * @return the value of bi_huaxiang.date_cd
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Date getDateCd() {
        return dateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.date_cd
     *
     * @param dateCd the value for bi_huaxiang.date_cd
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setDateCd(Date dateCd) {
        this.dateCd = dateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.product_system
     *
     * @return the value of bi_huaxiang.product_system
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public String getProductSystem() {
        return productSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.product_system
     *
     * @param productSystem the value for bi_huaxiang.product_system
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setProductSystem(String productSystem) {
        this.productSystem = productSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.new_user_cnt
     *
     * @return the value of bi_huaxiang.new_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getNewUserCnt() {
        return newUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.new_user_cnt
     *
     * @param newUserCnt the value for bi_huaxiang.new_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setNewUserCnt(Integer newUserCnt) {
        this.newUserCnt = newUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.old_user_cnt
     *
     * @return the value of bi_huaxiang.old_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getOldUserCnt() {
        return oldUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.old_user_cnt
     *
     * @param oldUserCnt the value for bi_huaxiang.old_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setOldUserCnt(Integer oldUserCnt) {
        this.oldUserCnt = oldUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.membercard_user_cnt
     *
     * @return the value of bi_huaxiang.membercard_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getMembercardUserCnt() {
        return membercardUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.membercard_user_cnt
     *
     * @param membercardUserCnt the value for bi_huaxiang.membercard_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setMembercardUserCnt(Integer membercardUserCnt) {
        this.membercardUserCnt = membercardUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.person_user_cnt
     *
     * @return the value of bi_huaxiang.person_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getPersonUserCnt() {
        return personUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.person_user_cnt
     *
     * @param personUserCnt the value for bi_huaxiang.person_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setPersonUserCnt(Integer personUserCnt) {
        this.personUserCnt = personUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.inst_user_cnt
     *
     * @return the value of bi_huaxiang.inst_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getInstUserCnt() {
        return instUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.inst_user_cnt
     *
     * @param instUserCnt the value for bi_huaxiang.inst_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setInstUserCnt(Integer instUserCnt) {
        this.instUserCnt = instUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.class_user_cnt
     *
     * @return the value of bi_huaxiang.class_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getClassUserCnt() {
        return classUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.class_user_cnt
     *
     * @param classUserCnt the value for bi_huaxiang.class_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setClassUserCnt(Integer classUserCnt) {
        this.classUserCnt = classUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.zfb_user_cnt
     *
     * @return the value of bi_huaxiang.zfb_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getZfbUserCnt() {
        return zfbUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.zfb_user_cnt
     *
     * @param zfbUserCnt the value for bi_huaxiang.zfb_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setZfbUserCnt(Integer zfbUserCnt) {
        this.zfbUserCnt = zfbUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.wxapp_user_cnt
     *
     * @return the value of bi_huaxiang.wxapp_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getWxappUserCnt() {
        return wxappUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.wxapp_user_cnt
     *
     * @param wxappUserCnt the value for bi_huaxiang.wxapp_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setWxappUserCnt(Integer wxappUserCnt) {
        this.wxappUserCnt = wxappUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.wxweb_user_cnt
     *
     * @return the value of bi_huaxiang.wxweb_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Integer getWxwebUserCnt() {
        return wxwebUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.wxweb_user_cnt
     *
     * @param wxwebUserCnt the value for bi_huaxiang.wxweb_user_cnt
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setWxwebUserCnt(Integer wxwebUserCnt) {
        this.wxwebUserCnt = wxwebUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.crt_time
     *
     * @return the value of bi_huaxiang.crt_time
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.crt_time
     *
     * @param crtTime the value for bi_huaxiang.crt_time
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_huaxiang.upd_time
     *
     * @return the value of bi_huaxiang.upd_time
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_huaxiang.upd_time
     *
     * @param updTime the value for bi_huaxiang.upd_time
     *
     * @mbg.generated Wed Nov 07 16:21:10 CST 2018
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }
}